server:
  port: 8081
  servlet:
    context-path: /middlestudy

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gaoxiang?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: gaoxiang
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      min-idle: 5
      max-active: 5
      max-wait: 5
      initial-size: 5
#      filters: stat,wall,log4j
  redis:
    host: localhost
    port: 6379
