server:
  port: 8081
  servlet:
    context-path: /middlestudy

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gaoxiang?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: gaoxiang
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      min-idle: 5
      max-active: 5
      max-wait: 5
      initial-size: 5
#      filters: stat,wall,log4j
  redis:
    host: localhost
    port: 6379

#  rabbitMQ 相关配置信息
  rabbitmq:
    virtual-host: / # 这里是做什么的 ？ 我也不是很清楚
    host: localhost
    port: 5672
    username: guest
    password: guest

#   rabbitMQ 实例配置信息
mq:
  env: local # 看起来像是类似 命名空间之类的东西
  basic:
    info:
      queue:
        name: ${mq.env}.queue
      exchange:
        name: ${mq.env}.exchange
      routing:
        name: ${mq.env}.key
  # 感觉这是一个问题 所有的队列处理信息都在 configure 里 而不是单独创建的类
  #  会不会是一个config 中只能配置一组绑定信息
  fanout:
    queue:
      one:
        name: ${mq.env}.middleware.mq.fanout.one.queue
      two:
        name: ${mq.env}.middleware.mq.fanout.two.queue
    exchange:
      name: ${mq.env}.middleware.mq.fanout.exchange
  # 消息自动回复类型
  auto:
    knowledge:
      queue:
        name: ${mq.env}.middleware.knowledge.queue.name
      exchange:
        name: ${mq.env}.middleware.knowledge.echange.name
      routing:
        name: ${mq.env}.middleware.knowledge.routing.name
  # 订单超时模块 死信队列配置
  order:
    dead:
      queue:
        name: ${mq.env}.dead.queue.name
      exchange:
        name: ${mq.env}.dead.exchange.name
      routing:
        name: ${mq.env}.dead.routing.name
    producer:
      order:
        exchange:
          name: ${mq.env}.produce.exchange.name
        routing:
          name: ${mq.env}.produce.routing.name
        real:
          queue:
            name: ${mq.env}.produce.queue.name

ouhou:
  object:
    info:
      queue:
        name: ${mq.env}.object.queue.info
      exchange:
        name: ${mq.env}.object.exchange
      routing:
        name: ${mq.env}.object.routing

# zookeeper 相关配置信息
# 按照书上的配置明显不是 spring 集成配置，而是直接连接的 zookeeper 服务器
zk:
  host: 127.0.0.1:2181
  namespace: middleware_distributeLock